CREATE TABLE unprinted_books (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title TEXT NOT NULL,
    author TEXT NOT NULL,
    cover_img TEXT,
    content jsonb,
    summary TEXT NOT NULL,
    price TEXT NOT NULL,
    date_created TIMESTAMPTZ DEFAULT now() NOT NULL
);